# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshAutocomplete < Formula
  desc "SSH host autocompletion helper for bash, zsh, and PowerShell"
  homepage "https://github.com/ordinlabs/ssh-autocomplete"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ordinlabs/ssh-autocomplete/releases/download/v1.0.0/ssh-autocomplete_1.0.0_darwin_amd64.tar.gz"
      sha256 "d8bc729b224d0ed0ecd1f691f7351bbf10f7e5bfed214557738494ec3d63ba66"

      define_method(:install) do
        bin.install "ssh-autocomplete"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ordinlabs/ssh-autocomplete/releases/download/v1.0.0/ssh-autocomplete_1.0.0_darwin_arm64.tar.gz"
      sha256 "565a7c03e7b689775148bf2dc47e3225c56a5015346a0753d6f2b5bb821ad638"

      define_method(:install) do
        bin.install "ssh-autocomplete"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ordinlabs/ssh-autocomplete/releases/download/v1.0.0/ssh-autocomplete_1.0.0_linux_amd64.tar.gz"
      sha256 "6330ca9e51ab64b902c4f2c18363fe4b926ec3891141aef8e241900654870651"
      define_method(:install) do
        bin.install "ssh-autocomplete"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ordinlabs/ssh-autocomplete/releases/download/v1.0.0/ssh-autocomplete_1.0.0_linux_arm64.tar.gz"
      sha256 "a4f30c5e37f309fa42a1ce5dc55673f9e64d1407850dbc42f278e567624fa4e7"
      define_method(:install) do
        bin.install "ssh-autocomplete"
      end
    end
  end
end
